baseURL = "http://docs.solo.io"
languageCode = "en-us"
title = "Documentation"

[module]
  proxy = "direct"
  # uncomment line below for temporary local development of module
  # replacements = "github.com/artberger/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.73.0"
  [[module.imports]]
    path = 'github.com/artberger/docsy'
    disable = false
  [[module.imports]]
    path = 'github.com/google/docsy/dependencies'
    disable = false
    
    
    


[params]

version_menu_pagelinks=true


# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Latest version (2.1.x)"

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
# Must match the value in brackets in "version_menu" above
version = "2.1.x"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "/mesh"
  
# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
# Set this to true on each git branch of stroom-docs that is not master, i.e. 6.1, 7.0, etc.
archived_version = true
  
  
# Add your release versions here
[[params.versions]]
  version = "main"
  url = "../main"

[[params.versions]]
  version = "latest (2.1.x)"
  url = "/../2.1.x"

[[params.versions]]
  version = "2.0.x"
  url = "/../2.0.x"
  

# Uncomment this if you have a newer GitHub repo with "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
github_branch = "main"


