baseURL = "http://docs.solo.io/"
languageCode = "en-us"
title = "Gloo Platform Documentation"

[module]
  proxy = "direct"
  # uncomment line below for temporary local development of module
  # replacements = "github.com/artberger/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.73.0"
  [[module.imports]]
    path = 'github.com/artberger/docsy'
    disable = false
  [[module.imports]]
    path = 'github.com/google/docsy/dependencies'
    disable = false
    




